<?php

namespace AppBundle\Repository;

/**
 * CheckInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckInRepository extends \Doctrine\ORM\EntityRepository
{

}
