<?php

namespace AppBundle\Repository;

/**
 * CheckInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckInRepository extends \Doctrine\ORM\EntityRepository
{

    public function updatescore($idf,$idu)
    {
        $req = $this->getEntityManager()->createQuery(

            "update AppBundle:MembresDefis m set m.score = m.score + 1
     where m.idDefis=:p and m.idUser=:s")
            ->setParameter('p',$idf)
        ->setParameter('s',$idu);

        return $req->execute();
    }
}
