<?php

namespace AppBundle\Repository;

/**
 * DefisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefisRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindDisc($id)
    {
        $req = $this->getEntityManager()->createQuery(
            "select  m from AppBundle:Discussion m where m.idDefis=:p"
        )->setParameter('p',$id);
        return $req->getResult();

    }
    public function existBattle($idf , $idu)
    {
        $req = $this->getEntityManager()->createQuery(
            " SELECT COUNT(u)
             FROM AppBundle:MembresDefis u
                   WHERE u.idDefis=:p and u.idUser=:t"
        )->setParameter('p',$idf)
        ->setParameter('t',$idu);
        return $req->getResult();

    }
}
