<?php

namespace AppBundle\Repository;

/**
 * MembresDefisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresDefisRepository extends \Doctrine\ORM\EntityRepository
{
   
}
