<?php

namespace AppBundle\Repository;

/**
 * OutilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutilsRepository extends \Doctrine\ORM\EntityRepository
{


    public function imc($taille , $poids ){


        $imc = $poids / ($taille * $taille);
        return $imc ;




    }

}
