<?php

namespace AppBundle\Repository;

/**
 * questionQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionQuizRepository extends \Doctrine\ORM\EntityRepository
{
}
