<?php

namespace AppBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{

    function findreclamation()
    {

        $query=$this->getEntityManager()->createQuery("select r from AppBundle:Reclamation r WHERE r.confirmation= 0 ");
        return $query->getResult();
    }

    function calculnbreclamation($idService)
    {
        $query=$this->getEntityManager()->createQuery("select COUNT(r.confirmation) from AppBundle:Reclamation r WHERE r.idService=$idService and r.confirmation= 1 ");
        return $query->getResult();
    }
}
