<?php

namespace AppBundle\Repository;

/**
 * resulatQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resulatQuizRepository extends \Doctrine\ORM\EntityRepository
{
}
