<?php
/**
 * Created by PhpStorm.
 * User: chayma
 * Date: 30/03/2018
 * Time: 21:49
 */

namespace AppBundle\Repository;
/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ServiceRepository extends \Doctrine\ORM\EntityRepository
{

     function findservice($idService)
    {
        $query=$this->getEntityManager()->createQuery("select s from AppBundle:Service s WHERE s.idService=:idService")->setParameter('idService',$idService);
        return $query->getResult();
    }

    function findServByRec(){
         $query=$this->getEntityManager()->createQuery("select s from AppBundle:Service s WHERE s.nbreclamation= 3");
         return $query->getResult();
    }

    function searchserviceByName($specialite)
    {
        $query=$this->getEntityManager()->createQuery("select s from AppBundle:Service s WHERE s.specialite LIKE :specialite")
            ->setParameter('specialite','%'.$specialite.'%');
        return $query->getResult();
    }
}